from django.conf.urls import include,url
from . import views

urlpatterns = [

	url(r'^$',views.index, name = 'home'),
	url(r'^landingpage',views.landingpage, name = 'lp'),
	url(r'^allrequest',views.All_request, name = 'allrequest'),
	url(r'^allreports/',views.Report_Detail, name = 'allreports'),
	url(r'^errordetail/',views.Error_detail, name = 'errordetail'),
	url(r'^otdetail/',views.OT_detail, name = 'otdetail'),
	url(r'^model/',views.modelview, name = 'modetltest'),
	url(r'^summary_tracker/',views.summary_tracker, name = 'summary'),
	url(r'^edf',views.filterdata, name = 'extractdatafilter'),
	url(r'^edf1',views.filterdata, name = 'extractdatafilter1'),
	url(r'^edit_staff_Detail',views.edit_staff_detail, name = 'editstaffdetail'),
	url(r'^view_Detail',views.view_staff_detail, name = 'viewDetail'),
	url(r'^internal_task_detail',views.internal_task_detail, name = 'internaltaskdetail'),
	url(r'^add_internal_task_detail',views.add_internal_task_detail, name = 'addinternaltaskdetail'),
	url(r'^edi_internal_task_detail/(?P<taskid>\d+)$',views.edit_internal_task_detail, name = 'editinternaltaskdetail'),
	url(r'^view_internal_task_option/(?P<taskid>\d+)$',views.view_internal_task, name = 'viewinternaltaskoption'),
	url(r'^edit_internal_task_option/(?P<choiceid>\d+)$',views.edit_internal_choice, name = 'editinternaltaskoption'),
	url(r'^add_internal_task_option/(?P<taskid>\d+)$',views.add_internal_choice, name = 'addinternaltaskoption'),
	url(r'^internal_task_with_choice/(?P<taskid>\d+)$',views.internal_task_with_choice, name = 'internaltaskwithchoice'),

	url(r'^feedback/(?P<reportid>\d+)/(?P<id>\d+)$',views.feedback, name = 'feedback'),
	url(r'^feedback_detail_id/(?P<reportid>\d+)$',views.Feedback_Detail_id, name = 'feedbackdetailid'),
	url(r'^feedback_detail',views.Feedback_Detail, name = 'feedbackdetail'),
	url(r'^about_team',views.about_team, name = 'aboutteam'),
	url(r'^what_we_do',views.whatwedo, name = 'whatwedo'),
	url(r'^governance_process',views.governanceprocess, name = 'governanceprocess'),
	url(r'^success_stories',views.successstories, name = 'successstories'),
	url(r'^comm_sugg',views.comm_sugg, name = 'comm_sugg'),
	url(r'^requestunapproved',views.unapproved, name = 'unapproved'),
	url(r'^requestapproved',views.approved, name = 'approved'),
	url(r'^requestassigned',views.assigned, name = 'assigned'),
	url(r'^requestoverview',views.overview, name = 'overview'),
	url(r'^requestestimate',views.estimate, name = 'estimate'),
	url(r'^requestwip',views.wip, name = 'wip'),
	url(r'^requestcompleted',views.completed, name = 'completed'),
	url(r'^requestrejected',views.rejected, name = 'rejected'),
	url(r'^request',views.RequestFormTemplate, name = 'loginrequest'),
	url(r'^request',views.RequestFormTemplate, name = 'addrequest'),
	url(r'^error_log/(?P<reportid>\d+)$',views.Error_Log, name = 'errorlog'),
	url(r'^status',views.check_status, name = 'checkstatus'),
	url(r'^otform/(?P<trackerid>\d+)$',views.ot_form, name = 'otform'),
	url(r'^thankyou/(?P<requestid>\d+)$',views.typage, name = 'ty'),
	url(r'^authorised/(?P<requestid>\d+)$',views.AuthorisedFormTemplate, name = 'authform'),
	url(r'^assignedform/(?P<requestid>\d+)$',views.RequestassigneddetailFormTemplate, name = 'assignedform'),
	url(r'^overview/(?P<requestid>\d+)$',views.OverviewFormTemplate, name = 'overviewform'),
	url(r'^report/',views.ReportForm, name = 'report'),
	url(r'^report/',views.ReportForm, name = 'addreport'),
	url(r'^estimation/(?P<requestid>\d+)$',views.EstimationFormTemplate, name = 'estimationform'),
	url(r'^estimationar/(?P<requestid>\d+)$',views.EstimationAcceptanceFormTemplate, name = 'estimationformar'),
	url(r'^completed/(?P<requestid>\d+)$',views.CompletedFormTemplate, name = 'completedform'),
	url(r'^rupdate/(?P<requestid>\d+)$',views.RequestdetailUpdate, name = 'rupdate'),
	url(r'^signup/', views.sign_up, name='signup'),
    url(r'^signin/', views.sign_in, name='signin'),
	url(r'^signout/', views.sign_out, name='signout'),
	url(r'^tracker', views.TimeTracker, name='timetracker'),
	url(r'^tracker', views.TimeTracker, name='tracker'),
	url(r'^sd', views.setdate, name='sdate'),
	url(r'^viewTracker/(?P<requestid>\d+)$', views.ViewTracker, name='viewtracker'),
	url(r'^editTracker/(?P<requestid>\d+)$', views.EditTracker, name='edittracker'),
	url(r'^editOT/(?P<requestid>\d+)$', views.EditOT, name='editot'),
	url(r'^editReport/(?P<requestid>\d+)$', views.EditReport, name='editreport'),
	url(r'^editErrorLog/(?P<requestid>\d+)$', views.EditError_Log, name='editerrorlog'),
	url(r'^editFeedback/(?P<feedbackid>\d+)$', views.EditFeedback, name='editfeedback'),
	url(r'^ajax/load-subcategories/', views.load_subcategories, name='ajax_load_subcategories'),
	url(r'^ajax/load-activity/', views.load_activity, name='ajax_load_activity'),
	url(r'^ajax/mimember_load_ajax/', views.load_mimember, name='ajax_load_mimember'),
	url(r'^ajax/load-datevalues/', views.load_datevalues, name='ajax_load_datavalues'),
	url(r'^ajax/load-tables/', views.load_tables, name='ajax_load_tables'),

	]
