USE [CentralMI]
GO

/****** Object:  Table [dbo].[options]    Script Date: 7/6/2018 12:06:24 PM ******/
DROP TABLE [dbo].[options]
GO

/****** Object:  Table [dbo].[options]    Script Date: 7/6/2018 12:06:24 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[options](
	[optionsid] [int] IDENTITY(1,1) NOT NULL,
	[optionsname] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[optionsid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[optionsname] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


