# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptrejectdetail',
            fields=[
                ('estacceptrejectid', models.AutoField(primary_key=True, serialize=False)),
                ('estacceptrejectdate', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'acceptrejectdetail',
            },
        ),
        migrations.CreateModel(
            name='Acceptrejectoption',
            fields=[
                ('acceptrejectoptionid', models.AutoField(primary_key=True, serialize=False)),
                ('acceptrejectoptionname', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'acceptrejectoption',
            },
        ),
        migrations.CreateModel(
            name='Assigneddetail',
            fields=[
                ('assignedid', models.AutoField(primary_key=True, serialize=False)),
                ('assigneddate', models.DateTimeField(db_column='assignedDate')),
            ],
            options={
                'managed': False,
                'db_table': 'assigneddetail',
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group',
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group_permissions',
            },
        ),
        migrations.CreateModel(
            name='Authorisedetail',
            fields=[
                ('authorisedid', models.AutoField(primary_key=True, serialize=False)),
                ('authoriseddate', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'authorisedetail',
            },
        ),
        migrations.CreateModel(
            name='Authoriserdetail',
            fields=[
                ('authoriserid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'authoriserdetail',
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_permission',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_groups',
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_user_permissions',
            },
        ),
        migrations.CreateModel(
            name='Completeddetail',
            fields=[
                ('completedid', models.AutoField(primary_key=True, serialize=False)),
                ('completeddate', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'completeddetail',
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_admin_log',
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'django_content_type',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_session',
            },
        ),
        migrations.CreateModel(
            name='Estimationdetail',
            fields=[
                ('estimationid', models.AutoField(primary_key=True, serialize=False)),
                ('estimationdate', models.DateTimeField()),
                ('estimateddays', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'estimationdetail',
            },
        ),
        migrations.CreateModel(
            name='Mimember',
            fields=[
                ('mimemberid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'mimember',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('optionsid', models.AutoField(primary_key=True, serialize=False)),
                ('optionsname', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'options',
            },
        ),
        migrations.CreateModel(
            name='Overviewdetail',
            fields=[
                ('overviewid', models.AutoField(primary_key=True, serialize=False)),
                ('overviewdate', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'overviewdetail',
            },
        ),
        migrations.CreateModel(
            name='Prioritydetail',
            fields=[
                ('requestpriorityid', models.AutoField(primary_key=True, serialize=False)),
                ('requestpriority', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'prioritydetail',
            },
        ),
        migrations.CreateModel(
            name='Requestcategorys',
            fields=[
                ('requestcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('requestcategorydatetime', models.DateTimeField()),
                ('requestcategorys', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'requestcategorys',
            },
        ),
        migrations.CreateModel(
            name='Requestdetail',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('requestraiseddate', models.DateTimeField()),
                ('requestdescription', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'requestdetail',
            },
        ),
        migrations.CreateModel(
            name='Requeststatusdetail',
            fields=[
                ('requeststatusid', models.AutoField(primary_key=True, serialize=False)),
                ('requeststatusdate', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'requeststatusdetail',
            },
        ),
        migrations.CreateModel(
            name='Requestsubcategory',
            fields=[
                ('requestsubcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('requestsubcategorydatetime', models.DateTimeField()),
                ('requestsubcategory', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'requestsubcategory',
            },
        ),
        migrations.CreateModel(
            name='Requesttypedetail',
            fields=[
                ('requesttypeid', models.AutoField(primary_key=True, serialize=False)),
                ('requesttype', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'requesttypedetail',
            },
        ),
        migrations.CreateModel(
            name='Statusdetail',
            fields=[
                ('statusnameid', models.AutoField(primary_key=True, serialize=False)),
                ('statusname', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'statusdetail',
            },
        ),
        migrations.CreateModel(
            name='Teamdetail',
            fields=[
                ('teamid', models.AutoField(primary_key=True, serialize=False)),
                ('teamdatetime', models.DateTimeField()),
                ('teamname', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'teamdetail',
            },
        ),
        migrations.CreateModel(
            name='Timetrackers',
            fields=[
                ('timetrackerid', models.AutoField(primary_key=True, serialize=False)),
                ('registerdatetime', models.DateTimeField()),
                ('trackingdatetime', models.DateTimeField()),
                ('task', models.CharField(blank=True, max_length=100, null=True)),
                ('description_text', models.CharField(blank=True, max_length=255, null=True)),
                ('totaltime', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('startdatetime', models.DateTimeField(blank=True, null=True)),
                ('stopdatetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'timetrackers',
            },
        ),
    ]
