# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverydays',
            fields=[
                ('deliverydaysid', models.AutoField(primary_key=True, serialize=False)),
                ('days', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'deliverydays',
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('frequencyid', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'frequency',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('reportid', models.AutoField(primary_key=True, serialize=False)),
                ('registereddate', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('deliverytime', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'reports',
            },
        ),
    ]
