# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0002_deliverydays_frequency_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emaildetail',
            fields=[
                ('emailid', models.AutoField(primary_key=True, serialize=False)),
                ('emaildate', models.DateTimeField()),
                ('stage', models.TextField()),
                ('emailsubject', models.TextField()),
                ('emailbody', models.TextField()),
                ('emailto', models.TextField()),
                ('emailfrom', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'emaildetail',
            },
        ),
    ]
