# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0003_emaildetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeDetail',
            fields=[
                ('timeid', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'time_detail',
            },
        ),
    ]
