# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0004_timedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fielddetail',
            fields=[
                ('fieldid', models.AutoField(primary_key=True, serialize=False)),
                ('tablename', models.CharField(max_length=255)),
                ('fieldname', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'fielddetail',
            },
        ),
        migrations.CreateModel(
            name='Filteroption',
            fields=[
                ('filterid', models.AutoField(primary_key=True, serialize=False)),
                ('filteroption', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'filteroption',
            },
        ),
    ]
