# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0006_errorlog_errortype_feedback_feedbackquestion_otdetail_otstatus_reporttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('reportid', models.AutoField(primary_key=True, serialize=False)),
                ('registereddate', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_days', models.IntegerField(blank=True, null=True)),
                ('deliverytime', models.TimeField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='DateTypes',
            fields=[
                ('date_typesid', models.AutoField(primary_key=True, serialize=False)),
                ('date_types', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'date_types',
            },
        ),
    ]
