# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0007_activity_datetypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activitystatus',
            fields=[
                ('activitystatusid', models.AutoField(primary_key=True, serialize=False)),
                ('activitystatus', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'activitystatus',
                'managed': False,
            },
        ),
    ]
