# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0008_activitystatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designationmaster',
            fields=[
                ('designationid', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'designationmaster',
                'managed': False,
            },
        ),
    ]
