# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0009_designationmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internalanswertype',
            fields=[
                ('internaltanswertypeid', models.AutoField(primary_key=True, serialize=False)),
                ('internaltaskanswertype', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'internalanswertype',
            },
        ),
        migrations.CreateModel(
            name='Internaltask',
            fields=[
                ('internaltaskid', models.AutoField(primary_key=True, serialize=False)),
                ('internaltaskdatetime', models.DateTimeField()),
                ('internaltaskquestion', models.CharField(db_column='internaltaskQuestion', max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'internaltask',
            },
        ),
        migrations.CreateModel(
            name='Internaltaskstatus',
            fields=[
                ('internaltaskstatusid', models.AutoField(primary_key=True, serialize=False)),
                ('internaltaskstatusdatetime', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'internaltaskstatus',
            },
        ),
    ]
