# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0010_internalanswertype_internaltask_internaltaskstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internaltaskchoice',
            fields=[
                ('internaltaskchoiceid', models.AutoField(primary_key=True, serialize=False)),
                ('internaltaskchoicedatetime', models.DateTimeField()),
                ('internaltaskchoice', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'internaltaskchoice',
            },
        ),
    ]
