# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0011_internaltaskchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('daytype', models.CharField(blank=True, max_length=50, null=True)),
                ('weekname', models.CharField(blank=True, max_length=50, null=True)),
                ('cd_wd_days', models.IntegerField(blank=True, db_column='CD_WD_days', null=True)),
                ('activityid', models.IntegerField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'activity_calendar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivitystatusCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activitystatusdate', models.DateTimeField()),
                ('activitycalendardate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activitystatus_calendar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('days_type', models.CharField(blank=True, db_column='Days Type', max_length=50, null=True)),
                ('daily', models.IntegerField(blank=True, db_column='Daily', null=True)),
                ('weekly', models.IntegerField(blank=True, db_column='Weekly', null=True)),
                ('monthly', models.IntegerField(blank=True, db_column='Monthly', null=True)),
                ('firstdayofmonth', models.DateField(blank=True, db_column='FIrstDayofmonth', null=True)),
                ('lastdayofthemonth', models.DateField(blank=True, db_column='LastDayoftheMonth', null=True)),
                ('weeknum', models.IntegerField(blank=True, db_column='WeekNum', null=True)),
                ('weekname', models.CharField(blank=True, db_column='WeekName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_Calendar',
                'managed': False,
            },
        ),
    ]
