# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0012_activitycalendar_activitystatuscalendar_tblcalendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('replydatetime', models.DateTimeField()),
                ('replyid', models.AutoField(primary_key=True, serialize=False)),
                ('reply', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'reply',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('suggestiondatetime', models.DateTimeField()),
                ('suggestionid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('suggestion', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'suggestion',
            },
        ),
        migrations.CreateModel(
            name='Whatwedo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(db_column='Data', max_length=255)),
                ('description', models.TextField(db_column='Description')),
                ('type', models.CharField(db_column='Type', max_length=100)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'whatwedo',
            },
        ),
    ]
