# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0013_reply_suggestion_whatwedo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governance',
            fields=[
                ('governancedatetime', models.DateTimeField()),
                ('governanceid', models.AutoField(primary_key=True, serialize=False)),
                ('processimg', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'governance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuccessStories',
            fields=[
                ('storiesdatetime', models.DateTimeField()),
                ('storiesid', models.AutoField(primary_key=True, serialize=False)),
                ('stories', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'success_stories',
                'managed': False,
            },
        ),
    ]
