# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0014_governance_successstories'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblNavbarFooterMaster',
            fields=[
                ('navbar_footer_id', models.AutoField(primary_key=True, serialize=False)),
                ('navbar_footer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('navbar_header_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_navbar_footer_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNavbarHeaderMaster',
            fields=[
                ('navbar_header_id', models.AutoField(primary_key=True, serialize=False)),
                ('navbar_header_name', models.CharField(blank=True, max_length=255, null=True)),
                ('navbar_header_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_navbar_header_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNavbarMaster',
            fields=[
                ('navbar_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_navbar_master',
                'managed': False,
            },
        ),
    ]
