# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0015_tblnavbarfootermaster_tblnavbarheadermaster_tblnavbarmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblConversation',
            fields=[
                ('conversationid', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('comments', models.TextField()),
            ],
            options={
                'db_table': 'tbl_conversation',
                'managed': False,
            },
        ),
    ]
