# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 18:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0016_tblconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblLeaveRecord',
            fields=[
                ('leaverecordid', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2018, 9, 18, 0, 20, 9, 524943))),
                ('leave_date', models.DateField()),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_leave_record',
            },
        ),
        migrations.CreateModel(
            name='TblLeaveType',
            fields=[
                ('leavetypeid', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2018, 9, 18, 0, 20, 9, 525439))),
                ('leave_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_leave_type',
            },
        ),
        migrations.CreateModel(
            name='UatDetail',
            fields=[
                ('uatid', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2018, 9, 18, 0, 20, 9, 525935))),
            ],
            options={
                'managed': False,
                'db_table': 'UAT_detail',
            },
        ),
        migrations.CreateModel(
            name='UatStatus',
            fields=[
                ('uat_status_id', models.AutoField(db_column='UAT_status_id', primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2018, 9, 18, 0, 20, 9, 526927))),
                ('uat_status', models.CharField(blank=True, db_column='UAT_status', max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'UAT_status',
            },
        ),
    ]
