# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0018_tblappreciation_tblrawactivitydetail_tblrawscore_tblrawteammaster_tblrawteammembermaster_tblteammetr'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblUsefulLinks',
            fields=[
                ('linkid', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('link', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_useful_links',
            },
        ),
    ]
