# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0021_validinvalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('imgid', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Gallery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IssueAction',
            fields=[
                ('issue_action_id', models.AutoField(db_column='Issue_Action_id', primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('issue', models.CharField(blank=True, db_column='Issue', max_length=255, null=True)),
                ('action_taken', models.CharField(blank=True, db_column='Action_taken', max_length=255, null=True)),
                ('targetdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Issue_Action',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publicholidays',
            fields=[
                ('holidaysid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('holidays_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'PublicHolidays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shiftupdate',
            fields=[
                ('updateid', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('updateinbrief', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ShiftUpdate',
                'managed': False,
            },
        ),
    ]
