# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 04:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0022_gallery_issueaction_publicholidays_shiftupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('calendar_days', models.IntegerField(blank=True, null=True)),
                ('calendar_weekday', models.IntegerField(blank=True, db_column='calendar_Weekday', null=True)),
                ('calendar_months', models.IntegerField(blank=True, null=True)),
                ('calendar_days_rest', models.IntegerField(blank=True, null=True)),
                ('working_days', models.IntegerField(blank=True, null=True)),
                ('working_weekday', models.IntegerField(blank=True, null=True)),
                ('working_months', models.IntegerField(blank=True, null=True)),
                ('working_days_rest', models.IntegerField(blank=True, null=True)),
                ('weeknum', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'calendar',
            },
        ),
        migrations.CreateModel(
            name='TblAcceptrejectdetail',
            fields=[
                ('estacceptrejectid', models.AutoField(primary_key=True, serialize=False)),
                ('estacceptrejectdate', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 570973))),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_acceptrejectdetail',
            },
        ),
        migrations.CreateModel(
            name='TblActivity',
            fields=[
                ('activityid', models.AutoField(primary_key=True, serialize=False)),
                ('registereddate', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 571965))),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_days', models.IntegerField(blank=True, null=True)),
                ('deliverytime', models.TimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('activitydocument', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_activity',
            },
        ),
        migrations.CreateModel(
            name='TblActivityCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('daytype', models.CharField(blank=True, max_length=50, null=True)),
                ('weekname', models.CharField(blank=True, max_length=50, null=True)),
                ('cd_wd_days', models.IntegerField(blank=True, db_column='CD_WD_days', null=True)),
                ('activityid', models.IntegerField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_activity_calendar',
            },
        ),
        migrations.CreateModel(
            name='TblActivitystatusCalendar',
            fields=[
                ('activitystatuscalendarid', models.AutoField(primary_key=True, serialize=False)),
                ('activitystatusdate', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 576429))),
                ('activitycalendardate', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_activitystatus_calendar',
            },
        ),
        migrations.CreateModel(
            name='TblAssigneddetail',
            fields=[
                ('assignedid', models.AutoField(primary_key=True, serialize=False)),
                ('assigneddate', models.DateTimeField(db_column='assignedDate', default=datetime.datetime(2018, 11, 17, 10, 25, 34, 580893))),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_assigneddetail',
            },
        ),
        migrations.CreateModel(
            name='TblAssignView',
            fields=[
                ('viewassign_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_assign_view',
            },
        ),
        migrations.CreateModel(
            name='TblAuthorisedetail',
            fields=[
                ('authorisedid', models.AutoField(primary_key=True, serialize=False)),
                ('authoriseddate', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 550705))),
            ],
            options={
                'managed': False,
                'db_table': 'authorisedetail',
            },
        ),
        migrations.CreateModel(
            name='TblAuthoriserdetail',
            fields=[
                ('authoriserid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'authoriserdetail',
            },
        ),
        migrations.CreateModel(
            name='TblCalendarHolidays',
            fields=[
                ('calendardate', models.DateTimeField(db_column='CalendarDate', primary_key=True, serialize=False)),
                ('calendarfunction', models.IntegerField(db_column='CalendarFunction')),
                ('holidaytype', models.CharField(blank=True, db_column='HolidayType', max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_calendar_holidays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCategorysMaster',
            fields=[
                ('requestcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('requestcategorydatetime', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 585357))),
                ('requestcategorys', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_categorys_master',
            },
        ),
        migrations.CreateModel(
            name='TblCompleteddetail',
            fields=[
                ('completedid', models.AutoField(primary_key=True, serialize=False)),
                ('completeddate', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 586845))),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_completeddetail',
            },
        ),
        migrations.CreateModel(
            name='TblDateTypesMaster',
            fields=[
                ('date_typesid', models.AutoField(primary_key=True, serialize=False)),
                ('date_types', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_date_types_master',
            },
        ),
        migrations.CreateModel(
            name='TblDeliveryDaysMaster',
            fields=[
                ('deliverydaysid', models.AutoField(primary_key=True, serialize=False)),
                ('days', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_delivery_days_master',
            },
        ),
        migrations.CreateModel(
            name='TblDesignationMaster',
            fields=[
                ('designationid', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_designation_master',
            },
        ),
        migrations.CreateModel(
            name='TblEmaildetail',
            fields=[
                ('emailid', models.AutoField(primary_key=True, serialize=False)),
                ('emaildate', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 591805))),
                ('stage', models.TextField()),
                ('emailsubject', models.TextField()),
                ('emailbody', models.TextField()),
                ('emailto', models.TextField()),
                ('emailfrom', models.TextField()),
                ('emailstatus', models.CharField(blank=True, max_length=255, null=True)),
                ('requeststatus', models.CharField(blank=True, db_column='RequestStatus', max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_emaildetail',
            },
        ),
        migrations.CreateModel(
            name='TblErrorlog',
            fields=[
                ('error_id', models.AutoField(primary_key=True, serialize=False)),
                ('errorlog_date', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 593292))),
                ('error_occurancedate', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 593292))),
                ('error_description', models.TextField()),
                ('errordocument', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_errorlog',
            },
        ),
        migrations.CreateModel(
            name='TblErrortypeMaster',
            fields=[
                ('error_typeid', models.AutoField(primary_key=True, serialize=False)),
                ('error_type', models.CharField(max_length=50)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_errortype_master',
            },
        ),
        migrations.CreateModel(
            name='TblEstimationdetail',
            fields=[
                ('estimationid', models.AutoField(primary_key=True, serialize=False)),
                ('estimationdate', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 596268))),
                ('estimateddays', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_estimationdetail',
            },
        ),
        migrations.CreateModel(
            name='TblFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_date', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 597909))),
                ('feedback_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_feedback',
            },
        ),
        migrations.CreateModel(
            name='TblFeedbackQuestion',
            fields=[
                ('feedback_questionid', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_questiondate', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 599762))),
                ('feedback_question', models.CharField(max_length=255)),
                ('feedback_answerdatatype', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_feedback_question',
            },
        ),
        migrations.CreateModel(
            name='TblFrequency',
            fields=[
                ('frequencyid', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_frequency',
            },
        ),
        migrations.CreateModel(
            name='TblGallery',
            fields=[
                ('imgid', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 602718))),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_gallery',
            },
        ),
        migrations.CreateModel(
            name='TblGovernance',
            fields=[
                ('governancedatetime', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 604701))),
                ('governanceid', models.AutoField(primary_key=True, serialize=False)),
                ('processimg', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_governance',
            },
        ),
        migrations.CreateModel(
            name='TblInternaltask',
            fields=[
                ('internaltaskid', models.AutoField(primary_key=True, serialize=False)),
                ('internaltaskdatetime', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 606685))),
                ('internaltaskquestion', models.CharField(db_column='internaltaskQuestion', max_length=255)),
                ('targetdate', models.DateTimeField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_internaltask',
            },
        ),
        migrations.CreateModel(
            name='TblInternaltaskchoice',
            fields=[
                ('internaltaskchoiceid', models.AutoField(primary_key=True, serialize=False)),
                ('internaltaskchoicedatetime', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 608173))),
                ('internaltaskchoice', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_internaltaskchoice',
            },
        ),
        migrations.CreateModel(
            name='TblInternaltaskstatus',
            fields=[
                ('internaltaskstatusid', models.AutoField(primary_key=True, serialize=False)),
                ('internaltaskstatusdatetime', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_internaltaskstatus',
            },
        ),
        migrations.CreateModel(
            name='TblIssueAction',
            fields=[
                ('issue_action_id', models.AutoField(db_column='Issue_Action_id', primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 566013))),
                ('issue', models.CharField(blank=True, db_column='Issue', max_length=255, null=True)),
                ('action_taken', models.CharField(blank=True, db_column='Action_taken', max_length=255, null=True)),
                ('targetdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_Issue_Action',
            },
        ),
        migrations.CreateModel(
            name='TblLeaveTypeMaster',
            fields=[
                ('leavetypeid', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 613133))),
                ('leave_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_leave_type_master',
            },
        ),
        migrations.CreateModel(
            name='TblMember',
            fields=[
                ('mimemberid', models.AutoField(primary_key=True, serialize=False)),
                ('teamdetail', models.IntegerField()),
                ('employeeid', models.IntegerField(blank=True, null=True)),
                ('dateofjoining', models.DateField(blank=True, db_column='DateofJoining', null=True)),
                ('dateofbirth', models.DateField(blank=True, db_column='DateofBirth', null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='PhoneNumber', max_length=10, null=True)),
                ('avatar', models.CharField(blank=True, db_column='Avatar', max_length=255, null=True)),
                ('aboutme', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_member',
            },
        ),
        migrations.CreateModel(
            name='TblOpenClose',
            fields=[
                ('activitystatusid', models.AutoField(primary_key=True, serialize=False)),
                ('activitystatus', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_open_close',
            },
        ),
        migrations.CreateModel(
            name='TblOptions',
            fields=[
                ('optionsid', models.AutoField(primary_key=True, serialize=False)),
                ('optionsname', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_options',
            },
        ),
        migrations.CreateModel(
            name='TblOtDetail',
            fields=[
                ('ot_id', models.AutoField(primary_key=True, serialize=False)),
                ('ot_startdatetime', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 623548))),
                ('ot_enddatetime', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 623548))),
                ('ot_hrs', models.IntegerField(blank=True, null=True)),
                ('otdocument', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_ot_detail',
            },
        ),
        migrations.CreateModel(
            name='TblOtStatus',
            fields=[
                ('ot_statusid', models.AutoField(primary_key=True, serialize=False)),
                ('ot_status', models.CharField(max_length=50)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_ot_status',
            },
        ),
        migrations.CreateModel(
            name='TblOverviewdetail',
            fields=[
                ('overviewid', models.AutoField(primary_key=True, serialize=False)),
                ('overviewdate', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 625533))),
                ('document', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_overviewdetail',
            },
        ),
        migrations.CreateModel(
            name='TblPriorityMaster',
            fields=[
                ('requestpriorityid', models.AutoField(primary_key=True, serialize=False)),
                ('requestpriority', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_priority_master',
            },
        ),
        migrations.CreateModel(
            name='TblPublicHolidaysMaster',
            fields=[
                ('holidaysid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('holidays_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_public_holidays_master',
            },
        ),
        migrations.CreateModel(
            name='TblReply',
            fields=[
                ('replydatetime', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 638429))),
                ('replyid', models.AutoField(primary_key=True, serialize=False)),
                ('reply', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_reply',
            },
        ),
        migrations.CreateModel(
            name='TblRequestdetail',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('requestraiseddate', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 640413))),
                ('requestdescription', models.TextField()),
                ('requestdocument', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_requestdetail',
            },
        ),
        migrations.CreateModel(
            name='TblRequeststatusdetail',
            fields=[
                ('requeststatusid', models.AutoField(primary_key=True, serialize=False)),
                ('requeststatusdate', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 642397))),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_requeststatusdetail',
            },
        ),
        migrations.CreateModel(
            name='TblRequesttypeMaster',
            fields=[
                ('requesttypeid', models.AutoField(primary_key=True, serialize=False)),
                ('requesttype', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_requesttype_master',
            },
        ),
        migrations.CreateModel(
            name='TblShiftUpdate',
            fields=[
                ('updateid', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 650333))),
                ('updateinbrief', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_shift_update',
            },
        ),
        migrations.CreateModel(
            name='TblStatusMaster',
            fields=[
                ('statusnameid', models.AutoField(primary_key=True, serialize=False)),
                ('statusname', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_status_master',
            },
        ),
        migrations.CreateModel(
            name='TblSubcategoryMaster',
            fields=[
                ('requestsubcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('requestsubcategorydatetime', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 654300))),
                ('requestsubcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('core_noncore', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_subcategory_master',
            },
        ),
        migrations.CreateModel(
            name='TblSuccessStories',
            fields=[
                ('storiesdatetime', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 656781))),
                ('storiesid', models.AutoField(primary_key=True, serialize=False)),
                ('stories', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_success_stories',
            },
        ),
        migrations.CreateModel(
            name='TblSuggestion',
            fields=[
                ('suggestiondatetime', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 658329))),
                ('suggestionid', models.AutoField(primary_key=True, serialize=False)),
                ('suggestion', models.TextField()),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_suggestion',
            },
        ),
        migrations.CreateModel(
            name='TblTeamMaster',
            fields=[
                ('teamid', models.AutoField(primary_key=True, serialize=False)),
                ('teamdatetime', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 665213))),
                ('teamname', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_team_master',
            },
        ),
        migrations.CreateModel(
            name='TblTimeTracker',
            fields=[
                ('timetrackerid', models.AutoField(primary_key=True, serialize=False)),
                ('registerdatetime', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 668189))),
                ('trackingdatetime', models.DateField()),
                ('task', models.CharField(blank=True, max_length=100, null=True)),
                ('description_text', models.CharField(blank=True, max_length=255, null=True)),
                ('totaltime', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('startdatetime', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 668685))),
                ('stopdatetime', models.DateTimeField(default=datetime.datetime(2018, 11, 17, 10, 25, 34, 669182))),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_time_tracker',
            },
        ),
        migrations.CreateModel(
            name='TblUatDetail',
            fields=[
                ('uatid', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_UAT_detail',
            },
        ),
        migrations.CreateModel(
            name='TblUatStatusMaster',
            fields=[
                ('uat_status_id', models.AutoField(db_column='UAT_status_id', primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('uat_status', models.CharField(blank=True, db_column='UAT_status', max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_UAT_status_master',
            },
        ),
        migrations.CreateModel(
            name='TblValidInvalidMaster',
            fields=[
                ('valid_invaidid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_valid_invalid_master',
            },
        ),
        migrations.CreateModel(
            name='TblViewTypeMaster',
            fields=[
                ('view_id', models.AutoField(primary_key=True, serialize=False)),
                ('viewname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_view_type_master',
            },
        ),
        migrations.CreateModel(
            name='TblWhatwedo',
            fields=[
                ('recordid', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.CharField(db_column='Data', max_length=255)),
                ('description', models.TextField(db_column='Description')),
                ('type', models.CharField(db_column='Type', max_length=100)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbL_whatwedo',
            },
        ),
        migrations.AlterModelTable(
            name='tblappreciation',
            table='tbl_appreciation',
        ),
        migrations.AlterModelTable(
            name='tblcalendar',
            table='tbl_calendar',
        ),
    ]
