# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0023_auto_20181117_1025'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tblauthorisedetail',
            table='tbl_authorisedetail',
        ),
    ]
