# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0024_auto_20181117_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblFeedbackQuestionMaster',
            fields=[
                ('feedback_questionid', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_questiondate', models.DateTimeField()),
                ('feedback_question', models.CharField(max_length=255)),
                ('feedback_answerdatatype', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_feedback_question_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblOtStatusMaster',
            fields=[
                ('ot_statusid', models.AutoField(primary_key=True, serialize=False)),
                ('ot_status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_ot_status_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblYesNo',
            fields=[
                ('optionsid', models.AutoField(primary_key=True, serialize=False)),
                ('optionsname', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tbl_yes_no',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='tblauthoriserdetail',
            table='tbl_authoriserdetail',
        ),
    ]
