# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-02 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralMI', '0025_auto_20181118_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblBusinessUnitMaster',
            fields=[
                ('bu_id', models.AutoField(db_column='BU_id', primary_key=True, serialize=False)),
                ('business_unit', models.CharField(blank=True, db_column='Business_Unit', max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_business_unit_master',
            },
        ),
    ]
